### PR TITLE
feat!: change stream muxer interface

### PR DESCRIPTION
**Pull request by mpetrunic**
@wemeetagain @achingbrain multistream-select is blocking updating muxer interface to use uint8arraylist

### CODE REVIEW

**Comment by wemeetagain** [comment]
Not seeing how its blocking this PR

**Comment by mpetrunic** [comment]
> Not seeing how its blocking this PR

Npm build fails 😅

**Comment by wemeetagain** [comment]
Is this blocked by https://github.com/libp2p/js-libp2p-interfaces/pull/278 ?

**Review by wemeetagain — APPROVED** [review]
lgtm

**Pull request merged**
